package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
)

// User is the resolver for the user field.
func (r *accessResolver) User(ctx context.Context, obj *Access) (*User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Target is the resolver for the target field.
func (r *accessResolver) Target(ctx context.Context, obj *Access) (Node, error) {
	panic(fmt.Errorf("not implemented: Target - target"))
}

// Access returns AccessResolver implementation.
func (r *Resolver) Access() AccessResolver { return &accessResolver{r} }

type accessResolver struct{ *Resolver }
