package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"errors"
)

// Owner is the resolver for the owner field.
func (r *fileResolver) Owner(ctx context.Context, obj *File) (*User, error) {
	return nil, errors.New("not implemented: Owner - owner")
}

// Parent is the resolver for the parent field.
func (r *fileResolver) Parent(ctx context.Context, obj *File) (*Folder, error) {
	return nil, errors.New("not implemented: Parent - parent")
}

// File returns FileResolver implementation.
func (r *Resolver) File() FileResolver { return &fileResolver{r} }

type fileResolver struct{ *Resolver }
