package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
)

// Owner is the resolver for the owner field.
func (r *folderResolver) Owner(ctx context.Context, obj *Folder) (*User, error) {
	panic(fmt.Errorf("not implemented: Owner - owner"))
}

// Parent is the resolver for the parent field.
func (r *folderResolver) Parent(ctx context.Context, obj *Folder) (*Folder, error) {
	panic(fmt.Errorf("not implemented: Parent - parent"))
}

// Children is the resolver for the children field.
func (r *folderResolver) Children(ctx context.Context, obj *Folder) ([]Node, error) {
	panic(fmt.Errorf("not implemented: Children - children"))
}

// Folder returns FolderResolver implementation.
func (r *Resolver) Folder() FolderResolver { return &folderResolver{r} }

type folderResolver struct{ *Resolver }
