package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
)

// GetNodeByURI is the resolver for the getNodeByURI field.
func (r *queryResolver) GetNodeByURI(ctx context.Context, uri string) (Node, error) {
	user, err := handleGettingUserFromContext(ctx, r.AuthN)
	if err != nil {
		return nil, err
	}

	node, err := r.SFS.GetNodeByURI(user, uri)
	if err != nil {
		return nil, fmt.Errorf("failed to get node at uri: %w", err)
	}

	return node, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
