name: sfs

services:
  app:
    build: app
    volumes:
      - ./app:/sfs/app
      - /sfs/app/node_modules
    ports:
      - "5173:5173"
  server:
    build: server
    volumes:
      - ./server:/sfs/server
    ports:
      - "8080:8080"
