name: sfs

services:
  app:
    build: app
    container_name: app
    env_file:
      - .env
    hostname: ${APP_HOSTNAME}
    ports:
      - 80:${APP_PORT}
    volumes:
      - ./app:/sfs/app
      - app_node_modules:/sfs/app/node_modules/

  server:
    build: server
    container_name: server
    env_file:
      - .env
    hostname: ${SERVER_HOSTNAME}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_DEBUG_PORT}:${SERVER_DEBUG_PORT}
    volumes:
      - ./server:/sfs/server
      - server_debug_bins:/sfs/server/__debug_bins/

  database:
    image: postgres:bullseye
    container_name: database
    env_file:
      - .env
    ports:
      - 5432:${DATABASE_PORT}

volumes:
  app_node_modules: null
  server_debug_bins: null
