version: "3"

name: sfs

services:
  server:
    profiles: [ develop ]
    image: sfs.server.debug:latest
    build:
      context: .
      target: debug
    ports:
      - "80:8080"
      - "9090:9090"
