# AccessType signifies read-only or read-write access to a node
enum AccessType {
  READ
  WRITE
}

# Access represents a user's access to a node.
type Access {
  user: User!
  type: AccessType!
  target: Node!
}
