# Folder is a node of the file system that holds other nodes.
type Folder implements Node {
  # Node fields
  id: ID!
  name: String!
  owner: User!
  parent: Folder

  # Folder field
  children: [Node!]!
}
