# Query is the root query type.
#
# It defines the interface in which clients will query the shared file system with.
type Query {
  getRoot: Folder!

  getNodeById(id: ID!): Node

  getFileById(id: ID!): File

  getFolderById(id: ID!): Folder
}
