// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccess = "access"

// Access mapped from table <access>
type Access struct {
	ID   string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	User string `gorm:"column:user;not null" json:"user"`
	Type string `gorm:"column:type;not null" json:"type"`
	Node string `gorm:"column:node;not null" json:"node"`
}

// TableName Access's table name
func (*Access) TableName() string {
	return TableNameAccess
}
