// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFile = "file"

// File mapped from table <file>
type File struct {
	ID      string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Node    string `gorm:"column:node;not null" json:"node"`
	Content string `gorm:"column:content;not null" json:"content"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
