// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID   string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
