# list available recipes
list:
  @just --list

# generate all code
all: graph migrate sqlc

# generate graphql code
graph:
	go generate ./graph

# generate sql schema migration
migrate:
	atlas migrate diff \
		--dir "file://db/migrations" \
		--to "file://db/schema.sql" \
		--dev-url "docker://postgres/16/dev"

# generate sqlc code
sqlc:
	sqlc generate -f db/sqlc.yml
