// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: CreateUser.sql

package models

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO public.user (name, salt, hash)
VALUES ($1, $2, $3)
RETURNING id, name, salt, hash
`

type CreateUserParams struct {
	Name string
	Salt []byte
	Hash []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Salt, arg.Hash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Salt,
		&i.Hash,
	)
	return i, err
}
