// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: CreateNode.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNode = `-- name: CreateNode :one
INSERT INTO node (owner, name, parent)
VALUES ($1, $2, $3)
RETURNING id, owner, name, parent
`

type CreateNodeParams struct {
	Owner  pgtype.UUID
	Name   string
	Parent pgtype.UUID
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode, arg.Owner, arg.Name, arg.Parent)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Parent,
	)
	return i, err
}
