// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: CreateUser.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO public.user (email, auth0_id)
VALUES ($1, $2)
RETURNING id, email, auth0_id
`

type CreateUserParams struct {
	Email   string
	Auth0ID pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Auth0ID)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Auth0ID)
	return i, err
}
