// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: GetUserByEmail.sql

package models

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, auth0_id
FROM public.user
WHERE "email" = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Auth0ID)
	return i, err
}
