// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: GetUserByName.sql

package models

import (
	"context"
)

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, salt, hash, auth0_id
FROM public.user
WHERE "name" = $1
LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Salt,
		&i.Hash,
		&i.Auth0ID,
	)
	return i, err
}
