// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: InsertRefreshToken.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_token (owner, hash, expiration)
VALUES ($1, $2, $3)
RETURNING id, owner, hash, creation, expiration
`

type InsertRefreshTokenParams struct {
	Owner      pgtype.UUID
	Hash       []byte
	Expiration pgtype.Timestamp
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.Owner, arg.Hash, arg.Expiration)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Hash,
		&i.Creation,
		&i.Expiration,
	)
	return i, err
}
