// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: InsertAccessToken.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAccessToken = `-- name: InsertAccessToken :one
INSERT INTO access_token (owner, hash, expiration)
VALUES ($1, $2, $3)
RETURNING id, owner, hash, creation, expiration
`

type InsertAccessTokenParams struct {
	Owner      pgtype.UUID
	Hash       []byte
	Expiration pgtype.Timestamp
}

func (q *Queries) InsertAccessToken(ctx context.Context, arg InsertAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRow(ctx, insertAccessToken, arg.Owner, arg.Hash, arg.Expiration)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Hash,
		&i.Creation,
		&i.Expiration,
	)
	return i, err
}
