// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccessType string

const (
	AccessTypeRead  AccessType = "read"
	AccessTypeWrite AccessType = "write"
)

func (e *AccessType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccessType(s)
	case string:
		*e = AccessType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccessType: %T", src)
	}
	return nil
}

type NullAccessType struct {
	AccessType AccessType
	Valid      bool // Valid is true if AccessType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccessType) Scan(value interface{}) error {
	if value == nil {
		ns.AccessType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccessType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccessType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccessType), nil
}

type Access struct {
	Accessor pgtype.UUID
	Target   pgtype.UUID
	Type     AccessType
}

type File struct {
	ID      pgtype.UUID
	Node    pgtype.UUID
	Content []byte
}

type Node struct {
	ID     pgtype.UUID
	Owner  pgtype.UUID
	Name   string
	Parent pgtype.UUID
}

type User struct {
	ID      pgtype.UUID
	Name    string
	Salt    []byte
	Hash    []byte
	Auth0ID pgtype.Text
}
